spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    username: test
    password: test
    port: 587
    properties.mail.smtp.starttls.enable: true