spring:
  profiles:
    active: heroku



  ################################################
  application:
    name: Shop Demo
  mail:
    host: ${MAIL_HOST} #smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT} #587
    properties.mail.smtp.starttls.enable: true
################################################
server:
  port: 8080
  use-forward-headers: true
